### ISSUE TITLE
Automatically pop up credentials dialog when needed.

### ISSUE THREAD

**Issue by benjamin-heasly** [isetbio/RemoteDataToolbox#24]
Sometimes users must supply a username and password to gain non-guest access to a repository.  We don't want to store these credentials on disk.  Instead, we can use `rdtCredentialsDialog()` to prompt for credentials.  We keep these credentials in memory and don't print them or write them to disk.

The toolbox should attempt to automatically pop up the credentials dialog when needed.  The pop up rule could be:
- Pop up the dialog when the configuration contains a blank password, and a non-blank, non-"guest" user name.

This rule should "do the right thing" 99% of the time.  I think?
- Users who only need guest access shouldn't have to bother with the pop up, so they can use a blank or "guest" username.
- Users who need to authenticate should use the pop up dialog, or find some other way to supply a password to the configuration.

**Comment by DavidBrainard** [comment]
It would be nice if the dialog only comes up for users who authenticate when they need to write.  That is, I should be able to validate isetbio without entering a password, as long as I am only reading.

DB

On Dec 8, 2015, at 11:36 AM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Sometimes users must supply a username and password to gain non-guest access to a repository. We don't want to store these credentials on disk. Instead, we can use rdtCredentialsDialog() to prompt for credentials. We keep these credentials in memory and don't print them or write them to disk.

The toolbox should attempt to automatically pop up the credentials dialog when needed. The pop up rule could be:
-   Pop up the dialog when the configuration contains a blank password, and a non-blank, non-"guest" user name.

This rule should "do the right thing" 99% of the time. I think?
-   Users who only need guest access shouldn't have to bother with the pop up, so they can use a blank or "guest" username.
-   Users who need to authenticate should use the pop up dialog, or find some other way to supply a password to the configuration.

**Comment by benjamin-heasly** [comment]
I agree, reading public data should not pop up the dialog.

But I think reading-vs-publishing might not always correspond to guest-vs-authenticated.  I would prefer not to bake this correspondence into the code.  For example, a user might want to authenticate before reading non-public data.  I think this is a useful situation for the toolbox to support, even if it's not our current goal with isetbio.

So I propose that the dialog behavior should depend on toolbox configuration, and not depend on whether the user is reading or publishing.

I think the way this would shake out is that most of the time you could use toolbox configuration with a "guest" user, and the toolbox would not prompt you for credentials.  But when you want to publish, you would have to specify different configuration with a real username, and then the toolbox would prompt you for your password.

I think this is roughly in line with the idea that publishing data is relatively unusual and performed by relatively special users.

How does that sound?

**Comment by benjamin-heasly** [comment]
12c94f1cbdac7d9c5e68a38ce6df0fcfe676dd46 pops up credentials dialog based on toolbox configuration.

The dialog pops up when the username is non-empty and non-"guest", and the password is empty.  Otherwise, the dialog doesn't pop up.  This happens at setup time, before the user does any reading or publishing.

Will leave this issue open since we might want to talk more about the desired popup behavior.

**Comment by DavidBrainard** [comment]
This sounds reasonable.  It might be useful to have a callable function that allows the user to enter credentials.  I think I might prefer to have the configuration generally not ask me, but then rather than switching configurations, just call some function to login, as it were.

Not completely sure.

On Dec 8, 2015, at 2:08 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree, reading public data should not pop up the dialog.

But I think reading-vs-publishing might not always correspond to guest-vs-authenticated. I would prefer not to bake this correspondence into the code. For example, a user might want to authenticate before reading non-public data. I think this is a useful situation for the toolbox to support, even if it's not our current goal with isetbio.

So I propose that the dialog behavior should depend on toolbox configuration, and not depend on whether the user is reading or publishing.

I think the way this would shake out is that most of the time you could use isetbio configuration with a "guest" user, and the toolbox would not prompt you for credentials. But when you want to publish, you would have to specify different configuration with a real username, and then the toolbox would prompt you for your password.

I think this is roughly in line with the idea that publishing data is relatively unusual and performed by relatively special users.

How does that sound?

**Comment by benjamin-heasly** [comment]
A callable function sounds great to me.

Now that I think of it, that's actually how one of the current examples works.
  https://github.com/isetbio/RemoteDataToolbox/blob/bshApi2/examples/brainard-archiva/rdtExamplePublishData.m#L39

It starts with a basic "guest" configuration, then calls the function to pop up the credentials dialog.  This results in a "logged in" version of the same configuration.

I would be happy to abandon this change and stick with the current behavior.

**Comment by benjamin-heasly** [comment]
To make this more complicated --

Another scenario that might be good to support is "logging in" for the duration of a Matlab session.  This seems natural for the user.

One similar feature we have now is the ability to "log in" to an RdtClient object, which means the user can enter credentials into a dialog once and not be bothered again for the lifetime of that object.  This seems fine when the user is working from a script where the RdtClient object is obvious.

But the client objects are not always obvious.  For example, when working with higher-level tools like the UnitTestToolbox, the objects may be created internally and stay hidden from the user.  So how would the user "log in" to these objects?

Is there a good place in Matlab to store "logged in" credentials?  Is there a good way to clear these credentials periodically or when Matlab shuts down?  Even if Matlab crashes?  What we'd need is the idea of a Matlab "user session", which is not the same as Matlab's global, persistent preferences mechanism.

**Comment by wandell** [comment]
This is a good topic for future security worries.  For now, with just a small number of us, the credentialsDialog seems good enough.  And we don't always dump out the password to screen (though we do sometimes, sigh).  This thread is stale enough that it seems to me we should close and discuss security another time, as we move forward.  Hence, closing.
