### ISSUE TITLE
Deleting not actually deleting

### ISSUE THREAD

**Issue by DavidBrainard** [isetbio/RemoteDataToolbox#36]
I deleted an artifact from the isetbio validation repository (validation/full/scene/sceneFromRGB).  It looked  like it went away from the dot user interface, and also looked gone from the slash user interface.

Here are screenshots to show I'm not making it up.

![screen shot 2015-12-29 at 12 32 11 pm](https://cloud.githubusercontent.com/assets/1158757/12038718/66aa8e66-ae28-11e5-8f73-f68956afb8e6.png)

<img width="532" alt="screen shot 2015-12-29 at 12 31 11 pm" src="https://cloud.githubusercontent.com/assets/1158757/12038725/6bbda672-ae28-11e5-8052-89220e25bcf6.png">

Then I ran a validation of that script.  This happily found the file and validated against it.

<img width="1169" alt="screen shot 2015-12-29 at 12 35 15 pm" src="https://cloud.githubusercontent.com/assets/1158757/12038747/a2f07d18-ae28-11e5-9d32-3ffa4b74aa58.png">\

I don't know if it is still finding it in my cache and not detecting that it has been deleted from the server, or whether the server is still serving it.

Even more confusing, if I open a new browser window with the dot interface, it comes back.  Here is a screen shot of that.

![screen shot 2015-12-29 at 12 36 40 pm](https://cloud.githubusercontent.com/assets/1158757/12038779/d553c314-ae28-11e5-912d-1f84b64593e4.png)

At the same time, the slash interface shows it as gone.

Hmmm.  Something is not working the way we expect it to.

(Note that deleting a validation file is how we update it -- we wanted to make this hard to do by accident.)

**Comment by DavidBrainard** [comment]
I bravely went into my grade cache directory and deleted the full/sceneFromRGB directory.  Once I did this, running the validation created and pushed up a new copy of the full validation file.  

So it looks like the caching is not playing nicely with what happens on the server.

**Comment by benjamin-heasly** [comment]
I think one problem is that the web UI (aka dot interface) is slow to update, which stinks.

Other than that, I think Gradle views it as correct to return the locally cached artifact even when the same artifact has been deleted from the server.  I think Gradle's mindset is more like "stockpiling goodies" rather than "syncing a remote folder".

Another way to handle updates instead of deleting existing artifacts could be to publish a new artifact with a new version number.  In that case, we would not have to worry about stale artifacts in the local cache because they would be old-but-correct-as-of-that-version.  And newer versions would be returned if/when available.

The update would still be explicit and hard to do by accident because the updater would have to supply the new version number.

But maybe using versions in this way is a different mindset that we have not talked about as a group.

**Comment by wandell** [comment]
A related part of the discussion is how we help people manage their local caches.

Joyce and I are uploading fairly large data sets to the archive (spectral radiance scenes).  I see that gradle keeps a local copy. I guess we need some way to help people clear out stuff they don't want, or perhaps to set a flag on the 'Publish' side, so that if you are pushing to the archive and don't want a local copy the local copy can be deleted at the time of the copy.

**Comment by DavidBrainard** [comment]
I do think we want some easy way to delete.  Maybe a Matlab command that will delete and artifact from both the repository and the local cache.  And perhaps another Matlab command that will simply clear the cache, or parts of it.  Or one that will scan the cache and get rid of anything that is no longer on the server.

I think the model that deleting won't happen often is OK, but I think we do want to be able to clean things up.

**Comment by benjamin-heasly** [comment]
OK, makes sense that we'd want to be able to control the local cache, too.

Nicolas also mentioned we should have delete functionality from the Matlab client: #29 .  Makes a lot of sense that if we initiate the delete from the client, we should clean up the local cache at the same time.

**Comment by benjamin-heasly** [comment]
https://github.com/isetbio/RemoteDataToolbox/pull/54 adds the ability to delete remote artifacts from the Matlab client.  It also cleans up the local cache so that subsequent reads will fail.  It adds an example script to demonstrate these new functions.

How does it look?

If/when we merge this, I think we could close this issue.

**Comment by benjamin-heasly** [comment]
https://github.com/isetbio/RemoteDataToolbox/pull/54 was merged!  I'm closing this.

See also #45, which we probably want to add next, so that deletes will be reflected in the web UI and list/search results.
