### ISSUE TITLE
listArtifacts - take a 'type' argument

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#41]
As I upload various data sets to the Archiva instance, I see that sometimes I want to find all the files (artifacts, ugh) of a certain type (e.g., Nikon *.nef files within the repository).  

I am having a hard time using either searchArtifacts or listArtifacts for that purpose.  Is the functionality in there?  Or could we add it?  Say, with the syntax

```
rd.listArtifacts(remotePath,'type','nef')
```

**Comment by wandell** [comment]
One more observation about downloading artifacts versus downloading via the url - 

% Downloading via the read artifact mechanism 
a = rd.listArtifacts;
tic
data = rd.readArtifact(a(2).artifactId,'type','tif');
toc
imtool(data);

> Elapsed time is 2.119284 seconds.

% Downloading from the url is significantly faster.
tic
tmp = tempname;
tmp = websave(tmp,a(2).url);
im = imread(tmp);
toc
imtool(im);

> Elapsed time is 0.593222 seconds.

**Comment by wandell** [comment]
One more thing I have learned and thought I should mention to all.

When putting files into Archiva, if two files have the same base name but different extensions, such as <name>.jpg and <name>.nef, they are considered to be part of the same artifact ID.  They appear as different 'artifacts' within that ID.  So, in a project with HJ we have associated files that are nef/pgm/jpg and the files (called artifacts) are stored within one artifact ID.

![screen shot 2015-12-31 at 11 10 21 am](https://cloud.githubusercontent.com/assets/1837145/12067477/24648a38-afaf-11e5-8309-1fe64a73eb4b.png)

**Comment by wandell** [comment]
Further testing relating to listArtifacts ...

Here is a remote path
   http://52.32.77.154/index.html#browse~scien/L3.Farrell.D200.garden

Running list artifacts does not find all the artifacts in the remote path.  Here is the code.

%% Create and login
rd = RdtClient('scien');
rd.credentialsDialog;
rd.crp('/L3/Farrell/D200/garden');

% Dump to screen
rd
Repository:     scien
User:           wandell
Repository URL: http://52.32.77.154/repository/scien/
Sever URL:      http://52.32.77.154/
Working path:   L3/Farrell/D200/garden

% Now the list.
% Many (always 30, which is suspicious) are returned 
% But several artifacts visible in the listing above are not returned:
%    Consider dsc_0767, dsc_0768, dsc_0769
% This is the code I executed. 
s = rd.listArtifacts;
idx = [];
for ii=1:length(a)
    if ~isempty(strfind('dsc_0767',a(ii).artifactId))  % 'dsc_0791' is found, but not dsc_0767
        idx = ii;
        break;
    end
end
idx

**Comment by wandell** [comment]
In fact, as I go higher in the hierarchy and include more and more artifacts, I am only returned a list of 30 by the rd.listArtifacts call.  But if I descend into, say, L3/Farrell/people all 5 are returned.  Hence, I am suspicious about the upper limit of 30.

**Comment by wandell** [comment]
When there are multiple files in an artifact (as above, jpg, nef, pgm) there is no indication in our returned artifact structure.  Not sure what to do about this.  Could be 
- we should never do this (like I did, inadvertently).  
- gradle offers some way to know whether there is one or more files in an artifact, and we can indicate in the returned artifact.

**Comment by benjamin-heasly** [comment]
9b632531eadd537b49088757262f2a2bacd1b9e8 addresses part of this.  Now the default limit for search results is raised from 30 to 1000.  And custom limits can be passed as the pageSize parameter to `listArtifacts()`.

**Comment by benjamin-heasly** [comment]
I am learning more about how to deal with multiple file types for an artifact.  I seems like a useful thing that we want to support.

Maven (and Archiva and Gradle) have the notion of an a "classifier".  This is a way to distinguish different files that belong to the same artifact.  The classifier is an arbitrary string.

Currently we are not providing any classifier when we publish artifacts.  I think this causes our tools to think that there is only one file per artifact.  If we start providing classifiers then I think Maven (and Archiva and Gradle) will be our friend.

In order to stay sane and throttle the number of concepts floating around, I think we should choose to always make the classifier the same as the file type / extension.

I ran a proof of concept.  Under a remote path called `classifiers`, I put 4 versions of the one artifact:
- `test.txt`
- `test.foo`
- `test.bar`
- `test.quux`

When I published each of these, I made the classifier equal to the file extension.

Here are the 4 files are in the Web UI (aka dot syntax) and in basic HTML (aka slash syntax):
- <a href="http://52.32.77.154/index.html#artifact-details-download-content~demo-repository/classifiers/test/1">Web UI</a>
- [plain HTML](http://52.32.77.154/repository/demo-repository/classifiers/test/1/)

Note that the Web UI Classifier column is filled in.  This was not the case for BW's and HJ's image files above.

So then I asked RemoteDataToolbox to list and read these artifacts.  It found all 4 of them!  I think this is what BW and HJ would have expected above, except they only got one.

```
>> listed = client.listArtifacts();
>> artifactIds = {listed.artifactId}

artifactIds = 

    'test'    'test'    'test'    'test'

>> types = {listed.type}

types = 

    'txt'    'quux'    'bar'    'foo'

>> [datas, fetched] = client.readArtifacts(arti);
datas
>> datas

datas = 

    'this is a txt file.'    'this is a quux file.'    'this is a bar file.'    'this is a foo file.'
```

So this is encouraging.  I want to spend more time exploring it.

One thing to note is that including the classifier changes the URL.  For example `.../my/group/test/1/test-1.txt` gets an extra `-txt` and becomes `.../my/group/test/1/test-1-txt.txt`.  This might be awkward since we already have lots of artifacts published without classifiers.  I'll think about this and try to make it not be a user problem.

I'll also try to find other things that the classifier might help or break.  For example, keyword searches?

**Comment by wandell** [comment]
I agree that file extensions should be the only classes.  There is a Matlab function (imformats) that returns the formats they support, if that is helpful at some point.

The image types that I (accidentally) placed in the same artifact had those image file extensions plus the Nikon Exchange Format (nef), which is the Nikon raw data format. These were posted to the scien repository in L3/Farrell/garden, for example.  Perhaps you would like to use that repository for testing out your ideas.  

I should also say that I can (and probably should) redo much of that L3 repository without a whole lot of trouble, and it may be the only one with multiple files in an artifact.  So, worrying about things breaking may not be that big a deal at this point (though others should squawk if they disagree).

Finally, one other things - DHB, NC and I probably need a lesson in how we should be using the fileVersion parameter.  After a little screwing around, I came to understand that fileVersion is actually a string rather than a version number.  I am not sure about the intention.  It might be that you would like to use fileVersion to denote 'jpg','nef' and so forth.   Though as things stand, multiple file types do get stored within a single 'fileVersion'.

**Comment by DavidBrainard** [comment]
I believe that both Nicolas and I can easily republish everything we have published, if it turns out that redoing things from the bottom up makes sense.  Nicolas can confirm or deny from his end.

DB

On Jan 5, 2016, at 8:07 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree that file extensions should be the only classes. There is a Matlab function (imformats) that returns the formats they support, if that is helpful at some point.

The image types that I (accidentally) placed in the same artifact had those image file extensions plus the Nikon Exchange Format (nef), which is the Nikon raw data format. These were posted to the scien repository in L3/Farrell/garden, for example. Perhaps you would like to use that repository for testing out your ideas.

I should also say that I can (and probably should) redo much of that L3 repository without a whole lot of trouble, and it may be the only one with multiple files in an artifact. So, worrying about things breaking may not be that big a deal at this point (though others should squawk if they disagree).

Finally, one other things - DHB, NC and I probably need a lesson in how we should be using the fileVersion parameter. After a little screwing around, I came to understand that fileVersion is actually a string rather than a version number. I am not sure about the intention. It might be that you would like to use fileVersion to denote 'jpg','nef' and so forth. Though as things stand, multiple file types do get stored within a single 'fileVersion'.

**Comment by wandell** [comment]
So, where do we stand with respect to 'types' inside of a single artifact?  I got distracted (by teaching, sigh).

As a reminder, right now I have jpg/pgm/nef files within an artifact that I access by screwing around with the artifact URL to set the extension.    I lost track of what I should be doing:  Is there an existing method within Ben's system, or I should reupload the files, or we are still discussing?

**Comment by benjamin-heasly** [comment]
I think we will be good to go forward with multiple file types inside a single artifact.  It just took me a day to work some of it out.

Adding the "classifier" to our artifacts caused Archiva's listing and searching functions to behave differently.  So I spend some time adjusting on the Matlab side and making sure all our tests still pass.

I would like to spend a little more time testing, then do a [merge](https://github.com/isetbio/RemoteDataToolbox/pull/46) Friday morning.  Then I'll come back with some more comments and pointers to examples.

Then I think what would be good is if you delete the current stuff in `scien/L3` and re-upload using updated RemoteDataToolbox code.  This will add the classifier to each image.  Then it should be the case that all images types are listable and searchable.  Also you should be able to filter on image type.

For other existing artifacts, where there is only one file per artifact, there should be no need to re-upload.  Hooray!  I modified our Gradle code to find artifacts with or without a classifier.

How does that sound?

**Comment by wandell** [comment]
Sounds great ... thanks!

I have scripts to redo the upload without any problem.  I probably don't need to delete, as we will just be overwriting existing data.  I will put this on my calendar for early next week.  I believe this system will be useful for many different people I know.  I am starting the sales job around here.  You are in a very advanced state, and maybe in a week or two I will be able to help with video/tutorial production, which can get us more people looking at features and ideas.

**Comment by benjamin-heasly** [comment]
Cool!  Thanks!

Actually, I think deleting the L3 stuff would be good because Archiva thinks foo-without-a-classifier and foo-with-a-classifier are different beings.  So it would not replace the existing files as expected.

Hrm, now that I say it, I think this applies to updates for all existing artifacts, whether they are single-file or multiple-files: when replacing artifacts older than 8 January 2016, please delete them first.  That way they will have classifiers.  After that, updates should work as expected.

This is an _update_ concern.  Listing, searching, and reading old and new artifacts should be fine.

**Comment by benjamin-heasly** [comment]
As of 041a694db377d91af09c5bc136d296fac0385196, I think we are good to go.

A new example [rdtExamplePublishMultiple](https://github.com/isetbio/RemoteDataToolbox/blob/master/examples/brainard-archiva/rdtExamplePublishMultiple.m) shows how to publish a collection of artifacts.  This includes the case where multiple files with the same name but different extensions go into a single artifact.  It also includes examples of listing and searching for these files, and restricting the results by file type.

A revised example [rdtExampleReadData](https://github.com/isetbio/RemoteDataToolbox/blob/master/examples/brainard-archiva/rdtExampleReadData.m) attempts to clarify and demonstrate expected usage when reading artifacts.  In particular, the fact that the reading functions require the `artifactId` as well as the `remotePath` for a given artifact.

I think this covers the issues raised in this thread related to artifacts, file types, listing, and searching.

How does it work?

**Comment by DavidBrainard** [comment]
I have regenerated all of the isetbio validation data and repushed up the two cone recording data files, using the new RDTB.  So those should all now be kosher.  I am not sure how to double check that they have the classifier field, so I didn’t do that.

On Jan 8, 2016, at 12:16 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Cool! Thanks!

Actually, I think deleting the L3 stuff would be good because Archiva thinks foo-without-a-classifier and foo-with-a-classifier are different beings. So it would not replace the existing files as expected.

Hrm, now that I say it, I think this applies to updates for all existing artifacts, whether they are single-file or multiple-files: when replacing artifacts older than 8 January 2016, please delete them first. That way they will have classifiers. After that, updates should work as expected.

This is an update concern. Listing, searching, and reading old and new artifacts should be fine.

**Comment by benjamin-heasly** [comment]
@wandell @DavidBrainard any objection to closing this issue?

**Comment by wandell** [comment]
Agreed.

Stanford

**Comment by DavidBrainard** [comment]
No objection.

DB

On Jan 13, 2016, at 3:13 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

@wandellhttps://github.com/wandell @DavidBrainardhttps://github.com/DavidBrainard any objection to closing this issue?
