### ISSUE TITLE
Ability to specify custom cache folder in rdt-config.json

### ISSUE THREAD

**Issue by npcottaris** [isetbio/RemoteDataToolbox#42]
It would be nice to be able to specify a custom location for the cache folder in the rdt-config.json config file. (I like to keep as much data as possible off my main SSD)

Is this currently possible? If so, what is the key name?
If not, can it be implemented easily?

Thanks,
Nicolas

**Comment by DavidBrainard** [comment]
See attached config file for how I am doing this.  I point at this file by its full path in my ieSetPreferences, also attached.  This setup does exactly what you want, and also makes it easy to go mess with the cache (e.g., delete files that need to be deleted) since it isn’t a hidden directory.

DB

On Dec 31, 2015, at 11:40 AM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:

It would be nice to be able to specify a custom location for the cache folder in the rdt-config.json config file. (I like to keep as much data as possible off my main SSD)

Is this currently possible? If so, what is the key name?
If not, can it be implemented easily?

Thanks,
Nicolas

**Comment by npcottaris** [comment]
There is no file attached. Can you please resend?
Thanks.

**Comment by DavidBrainard** [comment]
I guess you can’t send attachments as email responses to issues.  I’ll send to you directly.  If anyone else needs them, let me know.

DB

On Dec 31, 2015, at 11:58 AM, Nicolas Cottaris <notifications@github.com<mailto:notifications@github.com>> wrote:

There is no file attached. Can you please resend?
Thanks.

**Comment by npcottaris** [comment]
Perfect. Thanks!. 

For others: the field name is was looking for is "cacheFolder", so in the jason config file:
"cacheFolder": "/Users1/GradleCaches/isetbio"
