### ISSUE TITLE
remote path and retrieving an artifact (or artifacts)

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#48]
Working in ISETBIO, James and I had the experience that

% The readArtifact fails in this case
rd.crp('/resources');
parasol = rd.searchArtifacts('parasol');
data = rd.readArtifact(parasol.artifactId);

% But readArtifact succeeds in this case
rd.crp('/resources/data/rgc');
parasol = rd.searchArtifacts('parasol');
data = rd.readArtifact(parasol.artifactId);

% I kind of think BH would like us to use - which would be OK but it doesn't work yet ...
rd.crp('/resources');
parasol = rd.searchArtifacts('parasol');
rd.crp(parasol.remotePath);
data = rd.readArtifact(parasol.artifactId);

The problem is that for the case to work remotePath slot should begin with a '/'.  This doesn't seem to be the current behavior of artifact.  

One suggestion is to only use readArtifacts
   when only a single artifact is passed in return the structure rather than the cell array.  We could then make readArtifact simply go away.

**Comment by benjamin-heasly** [comment]
Ugh, I see how this is a bit awkward.

As a quick fix, how about:

```
rd.crp('/resources');
parasol = rd.searchArtifacts('parasol');
rd.crp(['/' parasol.remotePath]);
data = rd.readArtifact(parasol.artifactId);
```

I wonder if `crp()` is implemented wrong.  The leading slash is just there to tell `crp()` to set an absolute path, otherwise it appends to the working path.

But maybe appending to the working path is not important?  If that's the case, we could do away with the leading slash and make the default behavior of crp() to just set the whole working path.  In that case I think BW's third example would work as written.

Then if we do need to append to the working path, this could be a different method.  `arp()`?  Or we could abandon the analogy with shell command names and use method names like `setRemotePath()` and `appendRemotePath()`.  Only downside I see there is that I like saying "pwrp".
