### ISSUE TITLE
Downloading files with a nii.gz extension

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#59]
Over at vistasoft, Jon Winawer wrote

The addition of RemoteDataToolbox will be useful. But I am having some trouble using it with the example functional data set that was added.

For example, the code below produces an error. Does anyone know why?

rd = RdtClient('vistasoft');
rd.crp('/functional');
a = rd.listArtifacts;
data = rd.readArtifact(a(1).artifactId);
_Error using gradleFetchArtifact (line 136)
fetchPom Could not resolve all dependencies for configuration ':fetchPom'.
fetchWithClassifier Could not resolve all dependencies for configuration ':fetchWithClassifier'.
fetchWithoutClassifier Could not resolve all dependencies for configuration ':fetchWithoutClassifier'.

Error in rdtReadArtifact (line 50)
[localPath, pomPath, downloads] = gradleFetchArtifact(configuration.repositoryUrl, ...

Error in RdtClient/readArtifact (line 150)
[data, artifact, downloads] = rdtReadArtifact(obj.configuration, ..._

---

Brian responded -

I think I understand the issue.  I believe the error is this.  We need to include the file type in the rd.readArtifact argument (default type is 'mat').  The file we are retrieving is an nii.gz (I think), which we do not specify.  I have made this mistake several times, and I think many people will.  

Worse yet, I tried to classify the type as 'gz', which is how it appears in the web browser, but I the download still did not work.  So, I suspect that we do not a method for handling files with the 'nii.gz' extension.

Rather than me trying to debug this, I will alert Ben Heasly to the issue over on the RemoteDataToolbox repository (this message).  Ben understand this much better than me and is very efficient.  He will surely get back in a couple of days.

**Comment by benjamin-heasly** [comment]
Hello!  I tried this out myself.  I agree, the code as posted doesn't work :-1:   But I was able to make small changes and get it to work. :+1:  I'll post examples below.

I think this is another case where `readArtifact()` doesn't behave the way people expect (despite being perfectly wonderful in and of itself).  And what works is to provide more information to `readArtifact()` or else to use `readArtifacts()`-with-an-`s`.

So this is related to #48.  Also related to the example usages in [rdtExampleReadData](https://github.com/isetbio/RemoteDataToolbox/blob/master/examples/brainard-archiva/rdtExampleReadData.m).

**Comment by benjamin-heasly** [comment]
Here is what worked for me.  I'll paste the code in this comment and also attach a script.

```
% Reproduce RemoteDataToolbox issue number 59.

%% Set up.
clear;
clc;

% vistasoft config
%rd = RdtClient('vistasoft');

% I did this instead because I didn't have vistasoft config on my path
rd = RdtClient('brainard-archiva');
rd.configuration.repositoryUrl = 'http://52.32.77.154/repository/vistasoft';
rd.configuration.repositoryName = 'vistasoft';
rd.credentialsDialog();

% list vistasoft "functional" artifacts
rd.crp('/functional');
listedArtifacts = rd.listArtifacts();
art = listedArtifacts(1);

%% Fail to read artifact -- not enough info to find it.
[data, artifact] = rd.readArtifact(art.artifactId);

%% Succeed by providing more info to readArtifact().
%   it lives at "/functional/mrBOLD_01/Inplane", not "/functional"
%   it's classified as "gz", not "mat"
[data, artifact] = rd.readArtifact(art.artifactId, ...
    'remotePath', art.remotePath, ...
    'type', art.type);
disp(artifact)

%% Succeed by providing the whole artifact to readArtifacts()-with-an-s.
[dataCell, artifactArray] = rd.readArtifacts(art);
disp(artifactArray(1))
```

[rdt_issue_59_bsh.m.zip](https://github.com/isetbio/RemoteDataToolbox/files/114347/rdt_issue_59_bsh.m.zip)

**Comment by benjamin-heasly** [comment]
a4a4f964c9cad8a1ca8d961605e30557116f7e10 attempts to better document the expected usage.  It also prints some suggestions about remotePath and type, when `readArtifact()` fails.

I'm going to close this issue.  But happy to revisit if the documentation is still not enough, or if we think the actual API needs to change.

**Comment by wandell** [comment]
Hi Ben,

Good speaking with you!   I screwed around a little more, and this code runs correctly

% Open up and list, as before
rd = RdtClient('vistasoft');
rd.credentialsDialog;
rd.crp('/functional');
listedArtifacts = rd.listArtifacts();
art = listedArtifacts(1);

% The dataCell may NOT be right
[dataCell, artifactArray] = rd.readArtifacts(art);

  % But I can read the nifti file this way, by going to the directory and renaming the download
  [p,n,e] = fileparts(artifactArray(1).localPath);
  cd(p);
  tfile = [tempname,'.nii.gz'];
  copyfile([n,e],tfile);
  ni = niftiRead(tfile);

The reason for the earlier problem with the file read, it appears, is that the nifti file reader they distribute requires that the extensions be ".nii.gz" exactly, and the Archiva file has a different name from the one we upload.  This doesn’t conform.

At least the world is somewhat reasonable again. The data are moving up and down correctly, and by renaming the file we can read it.

I wonder if it is possible for the RDT to always make sure the file name that we send up to the server is preserved on return?

A couple of other little notes from our discussion
1.  The dataCell return doesn't seem quite right
2.  The artifact that is returned by readArtifacts is not exactly matched to the one that we send in
3.  We agree that you and I will move people toward using readArtifacts rather than readArtifact

**Comment by benjamin-heasly** [comment]
Hi Brian,

Thanks for figuring this out.  I agree with what you say and I have some ideas to add.

##### 1. About the data returned from readArtifacts()

Here is my summary of the situation.  When we read a familiar file type, like `tiff` or `mat`, we load the file immediately and return the data in a Matlab variable.  For other file types like `gz` it's less obvious how to load the data or what to return.  The current behavior is to load the file bytes wholesale into a char array.  This turns out to be confusing and not that useful.

I have some ideas what to do with unfamiliar file types, which I'll put in my next comment.

##### 2. About artifact info structs returned from different functions

You're right!  They are sometimes a bit different.  For example, `rdtListArtifacts()` returns urls that contain a file name and extension, something like this:

```
artifact.url : '/foo/bar/baz/1/quack-1-txt.txt
```

But `rdtReadArtifacts()` returns urls that omit the file name, something like this:

```
artifact.url : '/foo/bar/baz/1
```

The first way is probably better.  We should make all the urls include the file name and extension.

##### 3. About favoring `readArtifacts`-with-an-`s`

I agree, it makes sense just to use `readArtifacts`-with-an-`s` instead of thinking about which parameters to pass to `readArtifact`.

**Comment by benjamin-heasly** [comment]
Here are some ideas about what we can to when reading files of unfamiliar types.

Could you all let me know what you think of each idea?
- **Default**?
- **Accept a "loadFunction"**?
- **Accept a "destinationFolder"**?

##### Default

As a first cut, we can skip loading unfamiliar file bytes.  Instead of returning a big char array, we can just return the full path to the file.  The user will have to know to expect this, which might be confusing at first.  But it seems better than what we're doing now.

##### Accept a "loadFunction"

We should let users customize the file loading without having to modify the base code.  One way to do this would be to let `rdtReadArtifacts()` accept a "loadFunction" parameter.  This would be a function_handle, and the function would have to have a certain form.  Perhaps:

```
function data = myLoadFunction(artifactStruct)
```

Then a custom nifti reader might might look something like this:

```
myLoadFunction = @(art) readnifti(art.localPath);
[dataCell, artifactArray] = rd.readArtifacts(art, 'loadFunction', myLoadFunction);
```

`dataCell` would contain the return value from `myLoadFunction`.

##### Accept a "destinationFolder"

A special problem in this case is that nifti files have a double extension: `.nii` plus `.gz`.

This should be OK, except Gradle and Archiva only recognize `.gz` as the extension.  They treat `.nii` as part of the file name.  So when they rename the file for Maven bookkeeping, we get unexpected results:  `foo.nii.gz` becomes `foo.nii-1-gz.gz`.  This is no longer a `.nii.gz` file.  Alas!

I think we can fix this because the renaming is consistent.  Our code can probably find and remove the `-1-gz` and give back the original file name.

Only catch is I think we should not rename files inside the Gradle cache.  I think we should leave the Gradle cache to Gradle.  So if we want to do this renaming, I think we should copy the file out of the cache and put the renamed version in a folder specified by the user.

So how about a "destinationFolder" parameter for `rdtReadArtifacts()`?  When this folder is provided, the code will do the renaming and copying to this folder.  For example:

```
[dataCell, artifactArray] = rd.readArtifacts(art, 'destinationFolder', '/home/me/stuff');
disp(artifactArray)

artifactArray.localPath : '/home/me/stuff/foo.nii.gz
```

**Comment by wandell** [comment]
Very clear.  Thanks. I agree with your basic suggestion.  I am simply restating here.

You will
-  return the full path to the stored file
- allow the user to set a destination folder, and 
- when the destination folder is not the gradle folder we may change the name back to match the uploaded name (inverting Archiva's naming algorithm).

We might have the code be verbose, telling the user what is going on rather than counting on them to know to disp() the returned array.  Something like

```
fullPathCellArray = rd.readArtifacts(artifact,` 'destination',<dirName>)
RDT:  <ArtifactId> is stored as <file name> in directory <dirName>
```

**Comment by DavidBrainard** [comment]
As a general rule, I am not in favor of functions printing things into the command window, unless there is a clearly defined way to turn it on and off.  It is possible that Matlab’s “warning” faciliity is extensible, which might be a good mechanism for this.

On Feb 7, 2016, at 8:32 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:

Very clear. Thanks. I agree with your basic suggestion. I am simply restating here.

You will
-   return the full path to the stored file
-   allow the user to set a destination folder, and
-   when the destination folder is not the gradle folder we may change the name back to match the uploaded name (inverting Archiva's naming algorithm).

We might have the code be verbose, telling the user what is going on rather than counting on them to know to disp() the returned array. Something like

fullPathCellArray = rd.readArtifacts(artifact,` 'destination',<dirName>)
RDT:  <ArtifactId> is stored as <file name> in directory <dirName>

**Comment by wandell** [comment]
I agree, in general.  For this phase, though, I think we should start with these messages until we learn to control the code.  We can hide them with a call like

`[fullPath, msg] = rd.readArtifacts() ...
`

So when nargout == 2, we put into msg and otherwise we print.

The reason I suggest printing for now is that I and a few others are having a bit of a hard time getting the calling and return conventions right.  So, I need some training weels.We can delete the annoying messages once the interface settles.

**Comment by DavidBrainard** [comment]
This works for me.  Another alternative for the control of output is a ‘verbosity’,’level’ key pair arg scheme, which could be set initially by default to a level that causes this level of output and then we could change the default to ‘low’ or ‘quiet’ later.  Nicolas has used this scheme in other objects to good effect.

DB

On Feb 7, 2016, at 11:23 PM, Brian Wandell <notifications@github.com<mailto:notifications@github.com>> wrote:

I agree, in general. For this phase, though, I think we should start with these messages until we learn to control the code. We can hide them with a call like

[fullPath, msg] = rd.readArtifacts() ...

So when nargout == 2, we put into msg and otherwise we print.

The reason I suggest printing for now is that I and a few others are having a bit of a hard time getting the calling and return conventions right. So, I need some training weels.We can delete the annoying messages once the interface settles.

**Comment by benjamin-heasly** [comment]
Cool cool cool.  Thanks.

We already have a utility [rdtPrintf](https://github.com/isetbio/RemoteDataToolbox/blob/master/api/utilities/rdtPrintf.m) for printing stuff, conditional on a verbosity level.

So I'll add some print statements about what happened to the artifact, where it's located, etc.  I'll put these on "verbosity level one", ie "you have to turn them on".

You can set the verbosity level in the configuration struct/JSON:

```
{
  "serverUrl": "http://52.32.77.154/",
  "repositoryUrl": "http://52.32.77.154/repository/demo-repository/",
  ...
  "verbosity": 1
}

```

**Comment by benjamin-heasly** [comment]
Here's a PR aimed at this issue: https://github.com/isetbio/RemoteDataToolbox/pull/61

**Comment by wandell** [comment]
I accepted the PR just now.  Next up is documentation.  Onward!
