### ISSUE TITLE
Files without an extension

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#63]
Hi @benjamin-heasly 

I have a file (README) in an archive.  No extension.  The little chain of logic in rdtPublishArtifacts around line 80 breaks for that case.

Various options - what do you think we should do?  Main questions is this;  What file type should assign files with an extension?  Do we make up a type or do we just guess 'txt'?

**Comment by benjamin-heasly** [comment]
Hi @wandell 

If I could push pack a little bit, I am wondering if Archiva is the right place to put the README.  I think the motivation for remote data toolbox was to store large or binary files that don't fit well in Git.  All things equal, I think the README would be a good fit for Git.

Or maybe the README would still be happy if it were renamed to README.TXT?

I might be over-thinking it.  Having a README that lives with the data seems like a useful thing.  But I thought it was worth raising the question.

All that said, I will look into it.  Maybe we can just support this.  Or maybe there is some annoying reason why this would be hard...

**Comment by wandell** [comment]
OK.  I will add the txt extension in this case.

So you think we should generally require extensions?  If there is none, we should throw an error?   Not default to some other type?

Brian

Stanford
Sent from mobile device

On Feb 23, 2016, at 7:23 AM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Hi @wandellhttps://github.com/wandell

If I could push pack a little bit, I am wondering if Archiva is the right place to put the README. I think the motivation for remote data toolbox was to store large or binary files that don't fit well in Git. All things equal, I think the README would be a good fit for Git.

Or maybe the README would still be happy if it were renamed to README.TXT?

I might be over-thinking it. Having a README that lives with the data seems like a useful thing. But I thought it was worth raising the question.

All that said, I will look into it. Maybe we can just support this. Or maybe there is some annoying reason why this would be hard...

##

**Comment by benjamin-heasly** [comment]
Yes.  At least for now, I propose that we require an extension and throw an error when there is none.  We probably want a better error than the cryptic one that's currently thrown.

I think it might be hard to choose a default file type.  For example, some day I would like to publish renderer executables which on Linux would have no extension.  Renaming these to txt might be more confusing than helpful.

I looked into the code to see if we can "just support" files with no extension.  With some small changes I was able to publish a no-extension file.  But when I tried to view it in the Web UI, I got an error instead of seeing the file info.  When I tried to fetch the file from Matlab, Gradle failed silently without success or error.

So my impression is that our tools are not expecting to handle files without extensions.  We might be able to push harder and make this work anyway, but I'm not sure how much effort it would take.

So maybe we leave this be until there's a situation we can't work around?  Here are two workarounds I can think of:
- for text files, add a textish extension like txt, md, etc.
- for binaries like executables, zip the file before publishing.

I'll follow up with a pull request that has a better error message for no-extension publish.

**Comment by DavidBrainard** [comment]
Could we assign these file a type “no_extension” for purposes of archiva, and then strip it back off upon read.  I suppose this could cause confusion if anyone ever wanted a file of type “no_extension”, but I think I would be willing to take the risk.

DB

On Feb 23, 2016, at 1:30 PM, Ben Heasly <notifications@github.com<mailto:notifications@github.com>> wrote:

Yes. At least for now, I propose that we require an extension and throw an error when there is none. We probably want a better error than the cryptic one that's currently thrown.

I think it might be hard to choose a default file type. For example, some day I would like to publish renderer executables which on Linux would have no extension. Renaming these to txt might be more confusing than helpful.

I looked into the code to see if we can "just support" files with no extension. With some small changes I was able to publish a no-extension file. But when I tried to view it in the Web UI, I got an error instead of seeing the file info. When I tried to fetch the file from Matlab, Gradle failed silently without success or error.

So my impression is that our tools are not expecting to handle files without extensions. We might be able to push harder and make this work anyway, but I'm not sure how much effort it would take.

So maybe we leave this be until there's a situation we can't work around? Here are two workarounds I can think of:
-   for text files, add a textish extension like txt, md, etc.
-   for binaries like executables, zip the file before publishing.

I'll follow up with a pull request that has a better error message for no-extension publish.

**Comment by benjamin-heasly** [comment]
We could do this, but the no_extension would still be part of the file name in the Gradle cache.

I would like to leave files in the cache alone and not rename them.  So I think our first chance to strip off the no_extension would be if the user asked for the file to be copied to a "destinationFolder", which is an optional parameter of `rdtReadArtifact()`.

To me this means that sometimes we would strip off the no_extension, and sometimes we wouldn't, and this also seems confusing to me.

**Comment by benjamin-heasly** [comment]
Here is a PR that adds an explicit error message when trying to publish without a file extension.
https://github.com/isetbio/RemoteDataToolbox/pull/64

Maybe this is good enough for now?

I'm also totally happy to continue the conversation and come up with something better.

**Comment by wandell** [comment]
Thanks.  Onward.

Brian
