### ISSUE TITLE
Version management ... not understood.

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#66]
This evening I downloaded a matlab file, edited it, and then published it again.  I was hoping to over-write the original version.  Here is the web site

http://52.32.77.154/repository/isetbio/resources/scenes/multiband/scien/2004//Fruit_visible/1/ 

The original file was uploaded on 12/29/2015 and today is 3/2/2016.  The more recent file has a different file name. I am confused about these files, especially their naming conventions so that which one will be downloaded on a readArtifact call.  I would like to understand this so that I can write the manual clearly.

![screen shot 2016-03-01 at 8 58 32 pm](https://cloud.githubusercontent.com/assets/1837145/13451731/aa945daa-dff6-11e5-8d2c-ae27f376d6f9.png)

**Comment by benjamin-heasly** [comment]
Hi Brian,

I agree that's unfortunate and confusing.  Here's my understanding.

Going forward, you should be able to over-write files the way you want.

The confusion in this case came in when we added support for multiple file types.  We added the "classifer" to track the file type, which becomes part of the file name.  So now when you publish the update, you get the new file name instead of the original.

This confusion should only come up when updating files that were originally published before [January 6th 2015](https://github.com/isetbio/RemoteDataToolbox/commit/ee6632a35296678f3f82cd9cffd12294f297e3c5).

I think the fix in this case is just to delete the old file.  Looking at the [artifact link](http://52.32.77.154/repository/isetbio/resources/scenes/multiband/scien/2004//Fruit_visible/1/) you posted, it looks like the old file is already gone.  Did you delete it?

**Comment by wandell** [comment]
Yes, I did delete the older versions and just updated with the new files.

Are you pretty sure that there is value in the current very long file formats, in which the extension appears both in the name and as an extension?  I am taking a lot of grief from an important person in my life about this point.  I need a cease and desist argument.

Thanks,
Brian

**Comment by benjamin-heasly** [comment]
The long file names are constructed for us by our tools Gradle and Archiva.  The format comes from the Maven naming convention.

Our file names are especially long because we are using Maven "classifier"s to distinguish multiple file types within a single artifact.

The best reference I can find so far is in the [Maven Docs](https://maven.apache.org/plugins/maven-deploy-plugin/examples/deploying-with-classifiers.html).  It's not a great read, but it shows examples of "correct" file names which look like ours, with classifiers at the end of the file name.

The reason our file names look redundant is that we made the simplifying assumption that an artifact's classifier will always be the same as its file type.

I'm pretty sure there's value in this simplifying assumption.  I'm also pretty sure there's value in using the Maven conventions and existing tools like Gradle and Archiva.

So Modus Ponens, I'm pretty sure there's value in the current long file name format.
