### ISSUE TITLE
listRemotePaths

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#71]
@benjamin-heasly 

Many things are working, but unfortunately this listRemotePaths command is failing 

```
rd = RdtClient('isetbio');
rd.listRemotePaths

Response stream is undefined
 below is a Java Error dump (truncated):
Error using urlread2 (line 217)
Java exception occurred:
java.io.IOException: Server returned HTTP response code: 403 for URL:
http://52.32.77.154/restServices/archivaServices/searchService/getAllGroupIds?selectedRepos=isetbio
    at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)

Error in rdtRequestWeb (line 91)
        responseText = urlread2(encodedUrl, 'GET', '', headers, ...

Error in rdtListRemotePaths (line 36)
response = rdtRequestWeb(configuration, resourcePath, 'queryParams', params);

Error in RdtClient/listRemotePaths (line 77)
            remotePaths = rdtListRemotePaths(obj.configuration, varargin{:});
```

An example of a command that works is

`rd.openBrowser`

or even the more complex call

```
rd = RdtClient('isetbio');
rd.crp('/resources/scenes/hyperspectral/manchester_database/2002');

a = rd.listArtifacts('type','mat');
sData = rd.readArtifact(a(1),'type','mat');

%%
scene = sceneFromBasis(sData);
scene = sceneSet(scene,'name','Manchester 2002 scene1');
ieAddObject(scene); sceneWindow;
```

Sorry to bother you, but this is beyond my debugging knowledge.

**Comment by benjamin-heasly** [comment]
Hi @wandell .

Let me see -- the error is HTTP status 403, which means "forbidden".  So somehow there is an authorization problem when listing remote paths.

It is odd that you can list artifacts, but not list remote paths.  I maybe these two operations require different permissions in Archiva's view of the world.

I see your configuration is called "isetbio".  Is this the standard [isetbio configuration](https://github.com/isetbio/isetbio/blob/master/rdt-config-isetbio.json) with the "guest" account?

**Comment by benjamin-heasly** [comment]
OK, using the standard "isetbio" configuration I am able to reproduce the behavior you pasted above.  So there's a good chance I can fix today. #famouslastwords

**Comment by benjamin-heasly** [comment]
I did some testing and looked into the Archiva source code.

Indeed, the operation where we list remote paths has a restriction flag set ([source](https://github.com/apache/archiva/blob/master/archiva-modules/archiva-web/archiva-rest/archiva-rest-api/src/main/java/org/apache/archiva/rest/api/services/SearchService.java#L92)).  But the operation where we list artifacts does not ([source](https://github.com/apache/archiva/blob/master/archiva-modules/archiva-web/archiva-rest/archiva-rest-api/src/main/java/org/apache/archiva/rest/api/services/SearchService.java#L68)).

I don't know why these operations are treated differently.  But this explains why the guest user can't list remote paths.

Logged-in users _can_ list remote paths.  So that is a partial, quick workaround.  It also explains why our automated tests did not catch this bug.

I will implement a better fix where we list remote paths using alternative REST calls to Archiva, which are not restricted ([source](https://github.com/apache/archiva/blob/master/archiva-modules/archiva-web/archiva-rest/archiva-rest-api/src/main/java/org/apache/archiva/rest/api/services/BrowseService.java#L49)).

The new implementation will have to make multiple REST calls instead of one.  But this detail should be hidden by the toolbox so that our user-level Matlab scripts can stay the same.

**Comment by benjamin-heasly** [comment]
OK, I think I've fixed this;
- re-implemented `rdtListPaths()` with an alternative REST call that works with "guest" user
- added automated tests to be sure "guest" user can list paths
- pull request: https://github.com/isetbio/RemoteDataToolbox/pull/72

**Comment by benjamin-heasly** [comment]
I went ahead and merged the PR unilaterally.

@wandell would you please pull from master and try your script again?

**Comment by wandell** [comment]
The listRemotePaths function now works!  Great!

However, I was going to try logging in and try the function while logged in, too.

But ... the username and password that worked for me this weekend is now being rejected.  Any chance you understand that?

**Comment by wandell** [comment]
I should have added that this is the error

```
Response stream is undefined
 below is a Java Error dump (truncated):
Credentials not accepted:
Java exception occurred:
java.io.IOException: Server returned HTTP response code: 403 for URL: http://52.32.77.154/restServices/archivaServices/pingService/pingWithAuthz
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
```

**Comment by benjamin-heasly** [comment]
Oh, that's annoying about your password.  I think Archiva wants you to go to the web interface and reset your password.

... which Archiva is not supposed to be doing.  We encountered a password reset issue earlier this year, and it was irritating.  I thought I understood the problem and fixed it at the time.  Apparently I didn't succeed.

If you do reset your password I think you'll be able to keep working.  I will take another look at preventing this from happening every 3 months.

**Comment by wandell** [comment]
So, just coincidental timing.

Anyway, you were right.  I changed the password and I am back in business.

Thanks again for your help!

Brian
