### ISSUE TITLE
argument trapping, rdtPrintArtifactTable, bad programming form on my part

### ISSUE THREAD

**Issue by wandell** [isetbio/RemoteDataToolbox#73]
I added some functionality as part of managing the wiki pages.  I did various little things that probably should have made me issue a pull request.  I am putting this issue here as a flag to anyone who is watching the issues, but not the pushes.  Have a look at the ugly rdtPrintArtifactTable, sigh.

A general issue for me now is where we trap some of the arguments (in particular the artifact type).  Often the arguments are simply passed through the RdtClient call to the sub call without looking at them or using them.  Sometimes that is fine, but I now have some cases where I want type to be trapped and managed in RdtClient rather than simply passed through.  To discuss with Ben.

**Comment by benjamin-heasly** [comment]
I like `rdtPrintArtifactTable()`.  I'd be in favor of adding a "Version" column, since this is another coordinate that distinguishes an artifact/file from the others.

Moreover, thank you for the wiki pages!

---

I am also interested in the issue of trapping vs propagating arguments, for this and other toolboxes.  Sometimes it is natural and nice to propagate the whole `varargin` cell.  I like how this reduces typing and boilerplate code.  But I agree it is also the wrong thing to do sometimes.  It can make a mess.

I would like to have a concise syntax for "trap these arguments and propagate the rest", or vice-versa.  As far as I know this is a utility we'd have to write ourselves.  Maybe as a subclass of the built-in `inputParser` class.  Maybe we should go ahead and write this?

Do you want to do a Skype to talk about specific parts of `RdtClient`?

**Comment by benjamin-heasly** [comment]
I am closing this issue because it's old.  If we need to do more work in this area, let's create a new issue.
